baseurl = "/"
actualurl = "https://www.ssushant.in"
languageCode = "en-us"
title = "Random tech excursions"
theme = "kiera"

paginate = 10
paginatePath = "page"
disqusShortname = "oromin"
github = "mitra-varuna"

[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"
review = "/:year/:month/:day/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"
review = "reviews"

[author]
name = "Sushant Srivastava"

[params]
twitter = "ssushant"
googleAnalytics = "UA-62976890-1"
highlight = "default"
github = "mitra-varuna"
RSSEnabled = true
RSSSections = [ "Posts" ]
linkedin = "ssushant"
googleplus = "112420258095319874956"
disqusShortname = "orom.in"


[menu]
    [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/post/"

    [[menu.main]]
    name = "Tags"
    weight = 2
    identifier = "tags"
    url = "/tags/"

    [[menu.main]]
    name = "Reviews"
    weight = 3
    identifier = "reviews"
    url = "/review/"
[social]
  # Coding Communities
  github           = "mitra-varuna"
  # Visual Art Communities
  flickr           = ""
  # Social Networks
  instagram        = "sushant_post_cibum" # https://www.instagram.com/flowartsde/
