baseurl = "/"
actualurl = "http://www.ssushant.in"
languageCode = "en-us"
title = "Random Tech Excursions"
theme = "kiera"

paginate = 10
paginatePath = "page"
disqusShortname = "oromin"
github = "mitra-varuna"
googleAnalytics = "UA-62976890-1"

[permalinks]
post = "/:year/:month/:day/:slug/"
code = "/:slug/"
review = "/:year/:month/:day/:slug/"

[taxonomies]
tag = "tags"
topic = "topics"
review = "reviews"

[author]
name = "Sushant Srivastava"

[params]
twitter = "ssushant"
googleAnalytics = "UA-62976890-1"
highlight = "default"
github = "mitra-varuna"
RSSEnabled = true
RSSSections = [ "Posts" ]
linkedin = "ssushant"
googleplus = "112420258095319874956"
disqusShortname = "orom.in"
utterancesRepo = "mitra-varuna/ssushant-comments"                                                                                      
utterancesIssueTerm = "path"
pygmentsCodefencesGuessSyntax = true

[blackfriday]
extensions = ["hardLineBreak"]

[menu]
    [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "Tags"
    weight = 2
    identifier = "tags"
    url = "/tags/"

    [[menu.main]]
    name = "Reviews"
    weight = 3
    identifier = "reviews"
    url = "/reviews/"
[social]
  # Coding Communities
  github           = "sgundadhya"
  # Visual Art Communities
  flickr           = ""
  # Social Networks
  instagram        = "sushant_post_cibum" # https://www.instagram.com/flowartsde/
