# Site configuration for the Congo demo site
# --------------------------------------------------------------------------
# IMPORTANT: You should not use this file as a template for configuration
# as it does not contain all the required theme settings!
#
# Refer to the theme docs for configuration instructions if you're unsure.
# https://jpanther.github.io/congo/docs/
# --------------------------------------------------------------------------

baseurl = "https://ssushant.in"
actualurl = "https://www.ssushant.in"
languageCode = "en-us"
title = "Random Tech Excursions"
theme = "congo"
defaultContentLanguage = "en"
summaryLength = 0
paginate = 10
paginatePath = "page"
googleAnalytics = "UA-62976890-1"
enableSearch = true

[taxonomies]
  tag = "tags"
topic = "topics"
review = "reviews"

[params]
  # logo = "logo.jpg"
colorScheme = "congo"
[params.homepage]
  layout = "custom"
  showRecent = true
  mainSections = ["samples"]

[params.list]
  groupByYear = true
  showBreadcrumbs = true

[params.article]
  showBreadcrumbs = true
  showEdit = false
  editAppendPath = false
  showReadingTime = false

    [[menu.main]]
    name = "Posts"
    weight = 1
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "Tags"
    weight = 2
    identifier = "tags"
    url = "/tags/"

    [[menu.main]]
    name = "Reviews"
    weight = 3
    identifier = "reviews"
    url = "/reviews/"

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[verification]
google = "UA-62976890-1"
yandex = "87321204"
