
* Feedback or Unit Testing for Machine learning applications
  
** Unstable data (Seam testing)				       :oreilly_book:

** Underfitting (Cross-validation)

** Overfitting (Benchmark testing)  :Thoughful_machine_learning_oreilly_book:
   
** Unpredictable future (Precision/Recall tracking over time)

* Security OpenHouse (Akamai 10th December 2014)

** Akamai Intelligent Platform (Starbucks of the Network)

** DDOS Attack

*** Layer 4 attacks

** Web Application Firewall

*** Layer 7 security
    
*** SQL injection etc
    
**** Site Shield

**** Scrubbing centers by Prolexic (through BGP messages)
     
** DNS Service

*** FastDNS


** CSI (Cloud Security Intelligence)

*** Application Reputation

*** Proactive Information

**** Botnet Detection

* History of Analysis blog post

** Topological Space

*** general framework

*** notion of continuity

*** 20th century notion (Hausdorff)

*** Point set topology (Cantor's infinite sets)

*** Neighbourhood system

**** Three conditions for neighborhood of X

* Review Papers guidelines

** What is your take-away message from this paper?

** What is the motivation for this work? Why are the previous solutions inadequate?

** What logic, argument, evidence, artifacts (e.g., a proof-of-concept system), or experiments are presented in support of the idea?

** What is your analysis of the identified problem, idea and evaluation? Is this a good idea? What flaws do you perceive in the work? What are the most interesting or controversial ideas? For work that has practical implications, ask whether this will work, who would want it, what it will take to give it to them, and when might it become a reality?

** What are the paper’s contributions (author’s and your opinion)? Ideas, methods, software, experimental results, experimental

** What are future directions for this research (author’s and yours, perhaps driven by shortcomings or other critiques)?

** What questions are you left with? What questions would you like to raise in an open discussion of the work (review interesting and controversial points, above)? What do you find difficult to understand? List as many as you can)

* A/B testing tools

** Planout from Facebook

** Sixpack

** Petri

*** 

* Testing machine learning
** Seam testing input and output data
*** Testing input and Output data
** Underfitting vs Overfitting
** Precision vs Recall
** References

*** http://blog.mpacula.com/2011/02/17/unit-testing-statistical-software/
* Data Sources
** https://www.proteomicsdb.org
** http://littlesis.org










